version: '2'

services:
    project:
        build: ./docker-files/project
        container_name: home-framework-project
        environment:
            - XDEBUG_HOST=${XDEBUG_HOST}
            - XDEBUG_PORT=${XDEBUG_PORT}
            - XDEBUG_IDE_KEY=${XDEBUG_IDE_KEY}
        depends_on:
            - postgresql
        volumes:
            - .:/var/www
        ports:
             - 8000:80

    postgresql:
        image: postgres:9.5.6
        container_name: home-framework-postgresql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        volumes:
            - /var/lib/postgresql

    rabbit:
        image: rabbitmq:management
        container_name: home-framework-rabbit
        ports:
            - 5672:5672
            - 15672:15672
